const gridContainer = document.querySelector('#grid-container');

const One = document.createElement('div');
One.classList.add('grid-content');
gridContainer.appendChild(One);
const Two = document.createElement('div');
Two.classList.add('grid-content');
gridContainer.appendChild(Two);
const Three = document.createElement('div');
Three.classList.add('grid-content');
gridContainer.appendChild(Three);
const Four = document.createElement('div');
Four.classList.add('grid-content');
gridContainer.appendChild(Four);
const Five = document.createElement('div');
Five.classList.add('grid-content');
gridContainer.appendChild(Five);
const Six = document.createElement('div');
Six.classList.add('grid-content');
gridContainer.appendChild(Six);
const Seven = document.createElement('div');
Seven.classList.add('grid-content');
gridContainer.appendChild(Seven);
const Eight = document.createElement('div');
Eight.classList.add('grid-content');
gridContainer.appendChild(Eight);
const Nine = document.createElement('div');
Nine.classList.add('grid-content');
gridContainer.appendChild(Nine);
const Ten = document.createElement('div');
Ten.classList.add('grid-content');
gridContainer.appendChild(Ten);
const Eleven = document.createElement('div');
Eleven.classList.add('grid-content');
gridContainer.appendChild(Eleven);
const Twelve = document.createElement('div');
Twelve.classList.add('grid-content');
gridContainer.appendChild(Twelve);
const Thirteen = document.createElement('div');
Thirteen.classList.add('grid-content');
gridContainer.appendChild(Thirteen);
const Fourteen = document.createElement('div');
Fourteen.classList.add('grid-content');
gridContainer.appendChild(Fourteen);
const Fifteen = document.createElement('div');
Fifteen.classList.add('grid-content');
gridContainer.appendChild(Fifteen);
const Sixteen = document.createElement('div');
Sixteen.classList.add('grid-content');
gridContainer.appendChild(Sixteen);
const divBreak = document.createElement('div');
divBreak.classList.add('div-break');
gridContainer.appendChild(divBreak);


const Seventeen = document.createElement('div');
Seventeen.classList.add("grid-content");
gridContainer.appendChild(Seventeen);
const Eighteen = document.createElement('div');
Eighteen.classList.add("grid-content");
gridContainer.appendChild(Eighteen);
const Nineteen = document.createElement('div');
Nineteen.classList.add("grid-content");
gridContainer.appendChild(Nineteen);
const Twenty = document.createElement('div');
Twenty.classList.add("grid-content");
gridContainer.appendChild(Twenty);
const TwentyOne = document.createElement('div');
TwentyOne.classList.add("grid-content");
gridContainer.appendChild(TwentyOne);
const TwentyTwo = document.createElement('div');
TwentyTwo.classList.add("grid-content");
gridContainer.appendChild(TwentyTwo);
const TwentyThree = document.createElement('div');
TwentyThree.classList.add("grid-content");
gridContainer.appendChild(TwentyThree);
const TwentyFour = document.createElement('div');
TwentyFour.classList.add("grid-content");
gridContainer.appendChild(TwentyFour);
const TwentyFive = document.createElement('div');
TwentyFive.classList.add("grid-content");
gridContainer.appendChild(TwentyFive);
const TwentySix = document.createElement('div');
TwentySix.classList.add("grid-content");
gridContainer.appendChild(TwentySix);
const TwentySeven = document.createElement('div');
TwentySeven.classList.add("grid-content");
gridContainer.appendChild(TwentySeven);
const TwentyEight = document.createElement('div');
TwentyEight.classList.add("grid-content");
gridContainer.appendChild(TwentyEight);
const TwentyNine = document.createElement('div');
TwentyNine.classList.add("grid-content");
gridContainer.appendChild(TwentyNine);
const Thirty = document.createElement('div');
Thirty.classList.add("grid-content");
gridContainer.appendChild(Thirty);
const ThirtyOne = document.createElement('div');
ThirtyOne.classList.add("grid-content");
gridContainer.appendChild(ThirtyOne);
const ThirtyTwo = document.createElement('div');
ThirtyTwo.classList.add("grid-content");
gridContainer.appendChild(ThirtyTwo);
const divBreakOne = document.createElement('div');
divBreakOne.classList.add('div-break');
gridContainer.appendChild(divBreakOne);


const ThirtyThree = document.createElement('div');
ThirtyThree.classList.add('grid-content');
gridContainer.appendChild(ThirtyThree);
const ThirtyFour = document.createElement('div');
ThirtyFour.classList.add('grid-content');
gridContainer.appendChild(ThirtyFour);
const ThirtyFive = document.createElement('div');
ThirtyFive.classList.add('grid-content');
gridContainer.appendChild(ThirtyFive);
const ThirtySix = document.createElement('div');
ThirtySix.classList.add('grid-content');
gridContainer.appendChild(ThirtySix);
const ThirtySeven = document.createElement('div');
ThirtySeven.classList.add('grid-content');
gridContainer.appendChild(ThirtySeven);
const ThirtyEight = document.createElement('div');
ThirtyEight.classList.add('grid-content');
gridContainer.appendChild(ThirtyEight);
const ThirtyNine = document.createElement('div');
ThirtyNine.classList.add('grid-content');
gridContainer.appendChild(ThirtyNine);
const Fourty = document.createElement('div');
Fourty.classList.add('grid-content');
gridContainer.appendChild(Fourty);
const FourtyOne = document.createElement('div');
FourtyOne.classList.add('grid-content');
gridContainer.appendChild(FourtyOne);
const FourtyTwo = document.createElement('div');
FourtyTwo.classList.add('grid-content');
gridContainer.appendChild(FourtyTwo);
const FourtyThree = document.createElement('div');
FourtyThree.classList.add('grid-content');
gridContainer.appendChild(FourtyThree);
const FourtyFour = document.createElement('div');
FourtyFour.classList.add('grid-content');
gridContainer.appendChild(FourtyFour);
const FourtyFive = document.createElement('div');
FourtyFive.classList.add('grid-content');
gridContainer.appendChild(FourtyFive);
const FourtySix = document.createElement('div');
FourtySix.classList.add('grid-content');
gridContainer.appendChild(FourtySix);
const FourtySeven = document.createElement('div');
FourtySeven.classList.add('grid-content');
gridContainer.appendChild(FourtySix);
const FourtyEight = document.createElement('div');
FourtyEight.classList.add('grid-content');
gridContainer.appendChild(FourtyEight);
const FourtyNine = document.createElement('div');
FourtyNine.classList.add('grid-content');
gridContainer.appendChild(FourtyNine);
const divBreakTwo = document.createElement('div');
divBreakTwo.classList.add('div-break');
gridContainer.appendChild(divBreakTwo);

const Fifty = document.createElement('div');
Fifty.classList.add('grid-content');
gridContainer.appendChild(Fifty);
const FiftyOne = document.createElement('div');
FiftyOne.classList.add('grid-content');
gridContainer.appendChild(FiftyOne);
const FiftyThree = document.createElement('div');
FiftyThree.classList.add('grid-content');
gridContainer.appendChild(FiftyThree);
const FiftyFour = document.createElement('div');
FiftyFour.classList.add('grid-content');
gridContainer.appendChild(FiftyFour);
const FiftyFive = document.createElement('div');
FiftyFive.classList.add('grid-content');
gridContainer.appendChild(FiftyFive);
const FiftySix = document.createElement('div');
FiftySix.classList.add('grid-content');
gridContainer.appendChild(FiftySix);
const FiftySeven = document.createElement('div');
FiftySeven.classList.add('grid-content');
gridContainer.appendChild(FiftySeven);
const FiftyEight = document.createElement('div');
FiftyEight.classList.add('grid-content');
gridContainer.appendChild(FiftyEight);
const FiftyNine = document.createElement('div');
FiftyNine.classList.add('grid-content');
gridContainer.appendChild(FiftyNine);
const Sixty = document.createElement('div');
Sixty.classList.add('grid-content');
gridContainer.appendChild(Sixty);
const SixtyOne = document.createElement('div');
SixtyOne.classList.add('grid-content');
gridContainer.appendChild(SixtyOne);
const SixtyTwo = document.createElement('div');
SixtyTwo.classList.add('grid-content');
gridContainer.appendChild(SixtyTwo);
const SixtyThree = document.createElement('div');
SixtyThree.classList.add('grid-content');
gridContainer.appendChild(SixtyThree);
const SixtyFour = document.createElement('div');
SixtyFour.classList.add('grid-content');
gridContainer.appendChild(SixtyFour);
const SixtyFive = document.createElement('div');
SixtyFive.classList.add('grid-content');
gridContainer.appendChild(SixtyFive);
const SixtySix = document.createElement('div');
SixtySix.classList.add('grid-content');
gridContainer.appendChild(SixtySix);
const divBreakThree = document.createElement('div');
divBreakThree.classList.add('div-break');
gridContainer.appendChild(divBreakThree);

const SixtySeven = document.createElement('div');
SixtySeven.classList.add('grid-content');
gridContainer.appendChild(SixtySeven);
const SixtyEight = document.createElement('div');
SixtyEight.classList.add('grid-content');
gridContainer.appendChild(SixtyEight);
const SixtyNine = document.createElement('div');
SixtyNine.classList.add('grid-content');
gridContainer.appendChild(SixtyNine);
const Seventy = document.createElement('div');
Seventy.classList.add('grid-content');
gridContainer.appendChild(Seventy);
const SeventyOne = document.createElement('div');
SeventyOne.classList.add('grid-content');
gridContainer.appendChild(SeventyOne);
const SeventyTwo = document.createElement('div');
SeventyTwo.classList.add('grid-content');
gridContainer.appendChild(SeventyTwo);
const SeventyThree = document.createElement('div');
SeventyThree.classList.add('grid-content');
gridContainer.appendChild(SeventyThree);
const SeventyFour = document.createElement('div');
SeventyFour.classList.add('grid-content');
gridContainer.appendChild(SeventyFour);
const SeventyFive = document.createElement('div');
SeventyFive.classList.add('grid-content');
gridContainer.appendChild(SeventyFive);
const SeventySix = document.createElement('div');
SeventySix.classList.add('grid-content');
gridContainer.appendChild(SeventySix);
const SeventySeven = document.createElement('div');
SeventySeven.classList.add('grid-content');
gridContainer.appendChild(SeventySeven);
const SeventyEight = document.createElement('div');
SeventyEight.classList.add('grid-content');
gridContainer.appendChild(SeventyEight);
const SeventyNine = document.createElement('div');
SeventyNine.classList.add('grid-content');
gridContainer.appendChild(SeventyNine);
const Eighty = document.createElement('div');
Eighty.classList.add('grid-content');
gridContainer.appendChild(Eighty);
const EightOne = document.createElement('div');
EightOne.classList.add('grid-content');
gridContainer.appendChild(EightOne);
const EightTwo = document.createElement('div');
EightTwo.classList.add('grid-content');
gridContainer.appendChild(EightTwo);
const divBreakFour = document.createElement('div');
divBreakFour.classList.add('div-break');
gridContainer.appendChild(divBreakFour);

const EightThree = document.createElement('div');
EightThree.classList.add('grid-content');
gridContainer.appendChild(EightThree);
const EightFour = document.createElement('div');
EightFour.classList.add('grid-content');
gridContainer.appendChild(EightFour);
const EightFive = document.createElement('div');
EightFour.classList.add('grid-content');
gridContainer.appendChild(EightFour);
const EightSix = document.createElement('div');
EightSix.classList.add('grid-content');
gridContainer.appendChild(EightSix);
const EightSeven = document.createElement('div');
EightSeven.classList.add('grid-content');
gridContainer.appendChild(EightSeven);
const EightEight = document.createElement('div');
EightEight.classList.add('grid-content');
gridContainer.appendChild(EightEight);
const EightNine = document.createElement('div');
EightNine.classList.add('grid-content');
gridContainer.appendChild(EightNine);
const Ninety = document.createElement('div');
Ninety.classList.add('grid-content');
gridContainer.appendChild(Ninety);
const NinetyOne = document.createElement('div');
NinetyOne.classList.add('grid-content');
gridContainer.appendChild(NinetyOne);
const NinetyTwo = document.createElement('div');
NinetyTwo.classList.add('grid-content');
gridContainer.appendChild(NinetyTwo);
const NinetyThree = document.createElement('div');
NinetyThree.classList.add('grid-content');
gridContainer.appendChild(NinetyThree);
const NinetyFour = document.createElement('div');
NinetyFour.classList.add('grid-content');
gridContainer.appendChild(NinetyFour);
const NinetyFive = document.createElement('div');
NinetyFive.classList.add('grid-content');
gridContainer.appendChild(NinetyFive);
const NinetySix = document.createElement('div');
NinetySix.classList.add('grid-content');
gridContainer.appendChild(NinetySix);
const NinetySeven = document.createElement('div');
NinetySeven.classList.add('grid-content');
gridContainer.appendChild(NinetySeven);
const NinetyEight = document.createElement('div');
NinetyEight.classList.add('grid-content');
gridContainer.appendChild(NinetyEight);
const NinetyNine = document.createElement('div');
NinetyNine.classList.add('grid-content');
gridContainer.appendChild(NinetyNine);
const divBreakFive = document.createElement('div');
divBreakFive.classList.add('div-break');
gridContainer.appendChild(divBreakFive);

